### ISSUE TITLE
For mcm pipeline, Kabanero CRD wrapped as deployable is deleted after a pipeline run

### ISSUE THREAD

**Issue by oiricaud** [ibm-cloud-architecture/devops-demo-kabanero-pipelines#20]
Actual: 
MCM will initially deploy Kabanero (Appsody) application to target cluster successfully. Upon the execution of the MCM pipeline, the Deployable for the Kabanero application CRD is deleted and not updated to use the new image. 

Expected: 
MCM pipeline will update existing Appsody application to use newly built image.

**Comment by hollisc** [comment]
Closing this issue and will track it in repo (https://github.com/ibm-cloud-architecture/gse-devops).
