### ISSUE TITLE
Update default Kabanero pipelines to include additional stages

### ISSUE THREAD

**Issue by hollisc** [ibm-cloud-architecture/devops-demo-kabanero-pipelines#31]
Currently the "*-build-deploy-pl" kabanero pipelines out of the box will execute the following tasks: 

- validate-stack-task
- build-push-task
- image-scan-task
- deploy-task

Create a custom stack to include additional tasks so the order will be the following: 
- validate-stack-task
- test-task
- build-push-task
- image-scan-task
- deploy-task
- health-check-task
- java-pact-test-task
- gitops

Refer to this link for more info (https://kabanero.io/guides/working-with-pipelines/#creating-and-updating-your-own-tasks-and-pipelines).

```
When the product operator activates the CRD, it associates the pipelines in the pipelines archive with each of the stacks in the stack hub. The default pipelines are intended to work with all the stacks in the stack hub in the previous example. All of the pipeline-related resources (such as the tasks, trigger bindings, and pipelines) prefix the name of the resource with the keyword StackId. When the operator activates these resources, it replaces the keyword with the name of the stack it is activating.
```

**Comment by oiricaud** [comment]
Refer to this link to learn how to create a custom stack https://github.com/odrodrig/my-nodejs-express-stack/blob/master/customStack.md

**Comment by oiricaud** [comment]
Important to note this is for kabanero v0.9 -> https://kabanero.io/guides/working-with-pipelines/#creating-and-updating-your-own-tasks-and-pipelines

**Comment by oiricaud** [comment]
**Note**

I refactored `nodejs-mcm-pl` to `StackId-mcm-pl` and I get

```bash
\"StackId-mcm-pl\" is invalid: metadata.name: Invalid value: \"StackId-mcm-pl\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')} 
```

Not sure if this is due to mismatch on versions, the example shows v0.9 and we are using v0.6.1

**Comment by oiricaud** [comment]
@hollisc Quick question, should I do this for the pipelines as well or should I only do the tasks? 
<img width="248" alt="Screen Shot 2020-06-04 at 12 10 46 PM" src="https://user-images.githubusercontent.com/11867058/83789494-6d596a80-a65c-11ea-9227-e73963952b93.png">

**Comment by oiricaud** [comment]
We currently have the following stacks

- custom-node
- java-microprofile
- java-openlibery
- java-spring-boot2
- nodejs
- nodejs-express

I bound the directory [mcm-pipelines](pipelines/incubator/mcm-pipelines) to all of the stacks.

**Comment by oiricaud** [comment]
Update the naming convention from `nodejs-mcm` `StackId-mcm-pl-2`

**Comment by oiricaud** [comment]
@hollisc Can you take a look at the pull request #34
